#file: noinspection SpringBootApplicationYaml
  server.port: 8095
  spring.jpa.hibernate.ddl-auto: create
  spring.jpa.generate-ddl: true
  spring.datasource.url: jdbc:mysql://localhost:3306/serverdb?createDatabaseIfNotExist=true
  spring.datasource.username: root
  spring.datasource.password: 1851987
  spring.datasource.driver-class: com.mysql.cj.jdbc.Driver
  spring.jpa.show-sql: true
  spring.jpa.open-in-view: true
  #spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect
#server.port: 8090
#spring:
#  datasource:
#    password: 1851987
#    url: jdbc:mysql://localhost:3306/serverdb
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#          format_sql: true
#           org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#    generate-ddl: true
